# Metrics and Evaluation - California Housing Dataset

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim

x, y = fetch_california_housing(return_X_y=True, as_frame=True)

x.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:


x_train, x_testval, y_train, y_testval = train_test_split(x, y, test_size=0.2, random_state=42)
x_test, x_val, y_test, y_val = train_test_split(x_testval, y_testval, test_size=0.5, random_state=42)

In [ ]:
# Cap outliers based on IQR # yodo mover al modelo
cols = set(x.columns) - {"Longitude", "Latitude"}
Q1 = x_train.quantile(0.25)
Q3 = x_train.quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [ ]:
x_train_tensorial = torch.tensor(x_train, dtype=torch.float32)
y_train_tensorial = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

x_val_tensorial = torch.tensor(x_val, dtype=torch.float32)
y_val_tensorial = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

x_test_tensorial = torch.tensor(x_test, dtype=torch.float32)
y_test_tensorial = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

array([[0.36393308, 0.62745098, 0.46288192, ..., 0.7459508 , 0.01702128,
        0.72908367],
       [0.4368463 , 0.94117647, 0.3783391 , ..., 0.17213852, 0.12978723,
        0.61653386],
       [0.48218463, 0.05882353, 0.56048662, ..., 0.46147057, 0.22446809,
        0.38545817],
       ...,
       [0.32104761, 0.68627451, 0.3026969 , ..., 0.6402926 , 0.15744681,
        0.59462151],
       [0.68829073, 0.2745098 , 0.67694465, ..., 0.59530398, 0.53510638,
        0.23804781],
       [0.27371798, 1.        , 0.21193442, ..., 0.28098483, 0.55531915,
        0.19223108]], shape=(16512, 8))

In [ ]:
mean = torch.mean(x_train_tensorial, dim=0)
std = torch.std(x_train_tensorial, dim=0)

## Model Training and Evaluation

In [ ]:
# yodo: implementar sin psychiclearn


def evaluate_model(model, x, y):
    y_pred = model.predict(x)
    mae = mean_absolute_error(y, y_pred)
    mse = mean_squared_error(y, y_pred)
    rmse = root_mean_squared_error(y, y_pred)
    r2 = r2_score(y, y_pred)

    return {"MAE": mae, "MSE": mse, "R²": r2, "RMSE": rmse}

In [ ]:


train_metrics = evaluate_model(model, x_train_processed, y_train)
test_metrics = evaluate_model(model, x_test_processed, y_test)

metrics_df = pd.DataFrame({"Train": train_metrics, "Test": test_metrics})
metrics_df.T

            MAE       MSE        R²      RMSE
Train  0.492680  0.437935  0.672395  0.661767
Test   0.503701  0.472593  0.641096  0.687454

In [ ]:

model = 

model.fit(x_train_processed, y_train)

train_metrics = evaluate_model(model, x_train_processed, y_train)
test_metrics = evaluate_model(model, x_test_processed, y_test)

metrics_df = pd.DataFrame({"Train": train_metrics, "Test": test_metrics})
metrics_df.T

            MAE       MSE        R²      RMSE
Train  0.344071  0.251296  0.812013  0.501295
Test   0.359202  0.284462  0.783969  0.533350

In [22]:
val_metrics = evaluate_model(model, x_val_processed, y_val)
val_metrics

{'MAE': 0.3604550992008323,
 'MSE': 0.28642459634211664,
 'R²': 0.7802427043241614,
 'RMSE': 0.5351865061285801}